import {StyleSheet} from 'react-native';
import {
  ApplicationStyle,
  Colors,
  Fonts,
  horizontalScale,
  verticalScale,
} from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: horizontalScale(15),
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: verticalScale(5),
  },
  accountBox: {
    borderRadius: 10,
    padding: 14,
    ...ApplicationStyle.rowAlignCenterJustifyBetween,
    borderWidth: 1,
    borderColor: Colors.gray100,
  },
  accountTitle: {
    color: Colors.black100,
    fontSize: Fonts.size.regular,
    fontWeight: Fonts.Weight.medium,
  },
  accountAddress: {color: Colors.gray100, fontSize: 13},
  inputBox: {
    borderWidth: 1,
    borderColor: Colors.gray100,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: 14,
    height: 50,
    overflow: 'hidden',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tabs: {flexDirection: 'row', justifyContent: 'space-between', marginTop: 16},
  tabItem: {
    color: '#bbb',
    fontSize: 15,
    flex: 1,
    textAlign: 'center',
    paddingBottom: 6,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  accountList: {
    borderBottomWidth: 1,
    borderColor: Colors.gray50,
    padding: 14,
    marginVertical: 6,
    borderRadius: 10,
    ...ApplicationStyle.rowJustifyBetween,
  },
  balance: {color: Colors.black100, fontSize: 15},
  tag: {color: Colors.blue80, fontSize: 12, marginTop: 2},
  btnContainer: {
    ...ApplicationStyle.rowJustifyBetween,
    marginTop: 16,
    gap: horizontalScale(15),
  },
  cancelBtn: {
    backgroundColor: Colors.blue100,
    flex: 1,
    padding: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  continueBtn: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    marginLeft: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.gray80,
  },
});
