import {StyleSheet} from 'react-native';
import {
  ApplicationStyle,
  Colors,
  Fonts,
  horizontalScale,
  verticalScale,
  width,
} from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: horizontalScale(15),
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: verticalScale(5),
  },
  accountBox: {
    borderRadius: 10,
    padding: 14,
    ...ApplicationStyle.rowAlignCenterJustifyBetween,
    borderWidth: 1,
    borderColor: Colors.gray90,
  },
  accountTitle: {
    color: Colors.white80,
    fontSize: Fonts.size.regular,
    fontWeight: Fonts.Weight.low,
  },
  accountAddress: {color: Colors.btnColor, fontSize: 13},
  inputBox: {
    borderWidth: 1,
    borderColor: Colors.gray100,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: 14,
    height: 76,
    overflow: 'hidden',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tabs: {flexDirection: 'row', justifyContent: 'space-between', marginTop: 16},
  tabItem: {
    color: '#bbb',
    fontSize: 15,
    flex: 1,
    textAlign: 'center',
    paddingBottom: 6,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  accountList: {
    // borderBottomWidth: 1,
    // borderColor: Colors.gray50,
    padding: 14,
    marginVertical: 6,
    borderRadius: 10,
    ...ApplicationStyle.rowJustifyBetween,
  },
  balance: {color: Colors.gray80, fontSize: 15},
  tag: {color: Colors.blue80, fontSize: 12, marginTop: 2},
  btnContainer: {
    ...ApplicationStyle.rowJustifyBetween,
    marginTop: 16,
    gap: horizontalScale(15),
  },
  cancelBtn: {
    backgroundColor: Colors.purple100,
    flex: 1,
    padding: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  continueBtn: {
    flex: 1,
    padding: 10,
    borderRadius: 10,
    marginLeft: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.purple100,
  },

   tabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderBottomWidth: 1,
    paddingBottom: verticalScale(5),
    borderColor: Colors.black70,
    position: 'relative',
    marginTop: verticalScale(20),
  },
  tabView: {
    paddingBottom: verticalScale(5),
    position: 'relative',
    top: 5,
    width: width - horizontalScale(200),
  },
  activeTab: {
    borderBottomWidth: 1,
    borderColor: Colors.gray50,
  },
  tabText: {
    fontSize: Fonts.size.uprSemi,
    fontFamily: Fonts.type.montserratSemiBold,
    fontWeight: Fonts.Weight.seven,
    color: Colors.gray100,
    textAlign: 'center',
  },
  activeText: {
    color: Colors.white80,
  },
});
